name: "Akamai Netstorage Action"
description: "GitHub Action to upload to Akamai NetStorage via Akamai API's"
author: jdmevo123
inputs:
  uploadDirectory:
    description:  'Netstorage Upload Directory'
    required: true
  path:
    description: 'Path where build artifacts are stored. i.e. dir'
    required: true
  domainName:
    description: 'Upload account ID'
    required: true
  nspath:
    description: 'Path to where to upload NetStorage files. i.e. _site'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.uploadDirectory}}
    - ${{ inputs.path }}
    - ${{ inputs.domainName }}
    - ${{ inputs.nspath }}
branding:
  color: orange
  icon: upload-cloud
