name: "Akamai Jekyll Netstorage Action"
description: "GitHub Action to build Jekyll assets and upload to Akamai NetStorage via Akamai API's"
author: jdmevo123
inputs:
  uploadDirectory:
    description:  'Netstorage Upload Directory'
    required: true
  path:
    description: 'Path to where Jekyll files are built. i.e. _site'
    required: true
    default: '_site'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.uploadDirectory}}
    - ${{ inputs.path }}
branding:
  color: orange
  icon: trash-2
